//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ent_Genre
    {
        public int Id { get; set; }
        public int Entertainment_Id { get; set; }
        public int Genre_Id { get; set; }
    
        public virtual Entertainments Entertainments { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
